"""Pre-generated, archived haystacks for the probe.

A haystack is regenerated from a seed, and checking a fabrication claim has
meant rebuilding it from the seed in the result's filename. That is sound only
while the seed, the sizing tokenizer **and the generator code** are all
unchanged, and only the seed is recorded anywhere. Change the vocabulary or the
template and every historical seed yields different text, with no error.

So a run can instead read haystacks written to disk beforehand: one file per
(depth, rung, position, trial) and a manifest holding each file's sha256 and
expected answer, plus the generator version, the tokenizer and the vocabulary
digest. A replay refuses any file whose digest does not match -- an edited
haystack must fail loudly, not quietly become a different experiment -- and the
saved result records the manifest's own digest, so two cells can be shown to
have read identical bytes rather than assumed to have.

The archive is generated by the same loop, in the same order, as a live run
with the same seed, so a replayed run reads exactly the bytes the live one
would have built.
"""
from __future__ import annotations

import hashlib
import json
import os
import random
from typing import Any, Dict, List, Optional, Sequence, Tuple

MANIFEST = "manifest.json"

Key = Tuple[int, str, float, int]


class CorpusError(RuntimeError):
    """An archive that is missing, incomplete, or not what its manifest says."""


def sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def cells(depths: Sequence[int], rungs: Sequence[str], positions: Sequence[float],
          positionable: Sequence[str]) -> List[Tuple[int, str, float]]:
    """The (depth, rung, position) cells a run visits, in the order it visits them.

    Must match `probe.run`'s loop exactly: the haystacks are drawn from one
    sequential RNG, so visiting cells in a different order builds different
    text from the same seed.
    """
    return [(d, r, p) for d in depths for r in rungs
            for p in (positions if r in positionable else [0.5])]


def _name(depth: int, rung: str, position: float, trial: int) -> str:
    return f"d{depth}-{rung}-p{position:.3f}-t{trial:03d}.txt"


def build(out_dir: str, tokenizer: Any, tokenizer_name: str, seed: int,
          depths: Sequence[int], rungs: Sequence[str], positions: Sequence[float],
          trials: int, vocabulary: str = "builtin") -> Dict[str, Any]:
    """Write every haystack a run with these arguments would read, and a manifest."""
    from . import __version__
    from .probe import POSITIONABLE, build_context, names_for, vocabulary_digest

    if os.path.exists(os.path.join(out_dir, MANIFEST)):
        raise CorpusError(f"{out_dir} already holds a corpus; refusing to overwrite it")
    os.makedirs(out_dir, exist_ok=True)
    rng = random.Random(seed)
    names = names_for(vocabulary, seed)
    files: List[Dict[str, Any]] = []
    for depth, rung, position in cells(depths, rungs, positions, POSITIONABLE):
        for trial in range(trials):
            context, expected = build_context(tokenizer, depth, rung, rng, position,
                                              names)
            name = _name(depth, rung, position, trial)
            with open(os.path.join(out_dir, name), "w", encoding="utf-8") as fh:
                fh.write(context)
            files.append({"path": name, "depth": depth, "rung": rung,
                          "position": position, "trial": trial,
                          "sha256": sha256(context), "expected": expected})
    manifest = {
        "generator": __version__, "tokenizer": tokenizer_name,
        "vocabulary": vocabulary_digest(names), "vocabulary_kind": vocabulary,
        # The scorer needs the list itself, not only its digest: the hedging
        # rule demands exactly one of these names in a reply.
        "names": list(names), "seed": seed,
        "depths": list(depths), "rungs": list(rungs),
        "positions": list(positions), "trials": trials, "files": files,
    }
    with open(os.path.join(out_dir, MANIFEST), "w") as fh:
        json.dump(manifest, fh, indent=2)
    return manifest


class Archive:
    """A verified corpus, read back in run order."""

    def __init__(self, directory: str) -> None:
        path = os.path.join(directory, MANIFEST)
        try:
            with open(path, "rb") as fh:
                raw = fh.read()
        except OSError as exc:
            raise CorpusError(f"no corpus manifest at {path}") from exc
        self.directory = directory
        #: Digest of the manifest itself, recorded on every result that read it.
        self.digest = hashlib.sha256(raw).hexdigest()
        self.manifest: Dict[str, Any] = json.loads(raw)
        self._files: Dict[Key, Dict[str, Any]] = {}
        for f in self.manifest["files"]:
            self._files[(f["depth"], f["rung"], float(f["position"]), f["trial"])] = f
        self.verify()

    def verify(self) -> None:
        """Every file present and matching its digest, or refuse the whole archive."""
        bad = []
        for f in self.manifest["files"]:
            try:
                with open(os.path.join(self.directory, f["path"]), encoding="utf-8") as fh:
                    text = fh.read()
            except OSError:
                bad.append(f"{f['path']} (missing)")
                continue
            if sha256(text) != f["sha256"]:
                bad.append(f"{f['path']} (does not match its manifest digest)")
        if bad:
            raise CorpusError(
                f"corpus {self.directory} failed verification: {', '.join(bad[:5])}"
                + (f" and {len(bad) - 5} more" if len(bad) > 5 else ""))

    def take(self, depth: int, rung: str, position: float,
             trial: int) -> Tuple[str, Optional[str]]:
        f = self._files.get((depth, rung, float(position), trial))
        if f is None:
            raise CorpusError(
                f"corpus {self.directory} has no haystack for d{depth} {rung} "
                f"@{position} trial {trial}")
        with open(os.path.join(self.directory, f["path"]), encoding="utf-8") as fh:
            text = fh.read()
        # Re-checked at use, not only at load: a file changed after loading
        # must not slip into a trial.
        if sha256(text) != f["sha256"]:
            raise CorpusError(f"{f['path']} changed after the corpus was verified")
        return text, f["expected"]
